//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.07 at 03:10:17 PM IST 
//


package com.mindtree.pa.util;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mindtree.pa.util package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Problem_QNAME = new QName("", "problem");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mindtree.pa.util
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ProblemType }
     * 
     */
    public ProblemType createProblemType() {
        return new ProblemType();
    }

    /**
     * Create an instance of {@link CaseType }
     * 
     */
    public CaseType createCaseType() {
        return new CaseType();
    }

    /**
     * Create an instance of {@link TestType }
     * 
     */
    public TestType createTestType() {
        return new TestType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProblemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "problem")
    public JAXBElement<ProblemType> createProblem(ProblemType value) {
        return new JAXBElement<ProblemType>(_Problem_QNAME, ProblemType.class, null, value);
    }

}
